INSERT INTO DBUPDATE (SCRIPTID, AUTHOR, SCRIPTNAME)
VALUES ('2', 'Author', 'create_initial_tables');

CREATE TABLE USERINFO (
  ID        INT          NOT NULL AUTO_INCREMENT,
  EMAIL     VARCHAR(255) NOT NULL,
  PASSWORD  VARCHAR(255) NOT NULL,
  LASTNAME  VARCHAR(255) NOT NULL,
  FIRSTNAME VARCHAR(255) NOT NULL,
  SURNAME   VARCHAR(255) NULL,
  PRIMARY KEY (ID),
  UNIQUE INDEX EMAIL_UNIQUE (EMAIL ASC)
);

CREATE TABLE FUNCROLE (
  ID   INT         NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(45) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE INDEX NAME_UNIQUE (NAME ASC)
);

CREATE TABLE USERROLE (
  ID       INT         NOT NULL AUTO_INCREMENT,
  USERID   INT         NOT NULL,
  FUNCROLE VARCHAR(45) NOT NULL,
  PRIMARY KEY (ID),
  INDEX FK_USER_idx (USERID ASC),
  INDEX FK_FUNCROLE_idx (FUNCROLE ASC),
  CONSTRAINT FK_USER
  FOREIGN KEY (USERID)
  REFERENCES USERINFO (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_FUNCROLE
  FOREIGN KEY (FUNCROLE)
  REFERENCES FUNCROLE (NAME)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

INSERT INTO FUNCROLE (NAME)
VALUES ('ADMIN');

INSERT INTO FUNCROLE (NAME)
VALUES ('DEVELOPER');

INSERT INTO FUNCROLE (NAME)
VALUES ('USER');

INSERT INTO USERINFO (EMAIL, PASSWORD, LASTNAME, FIRSTNAME)
VALUES ('admin', '$2a$10$0KeGvn5LUpgHPzH42ZD5K.JjPhaw8JmX8hYOB7uDL0euj1KHNCAS.', 'admin', 'admin');

INSERT INTO USERROLE (USERID, FUNCROLE)
VALUES ((SELECT ID
         FROM USERINFO
         WHERE EMAIL = 'admin'), 'ADMIN');

